server:
  port: 8203
spring:
  data:
    mongodb:
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:27017}
      database: ${DB_NAME:trainee}
      user: ${DB_USER:''}
      password: ${DB_PASSWORD:''}
