server:
  port: 8203
  servlet:
    context-path: /trainee

spring:
  data:
    mongodb:
      uri: mongodb://${DB_USER:admin}:${DB_PASSWORD:pwd}@${DB_HOST:localhost}:${DB_PORT:27017}/${DB_NAME:trainee}?authSource=admin
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    ssl: ${REDIS_SSL:false}
    user: ${REDIS_USER:default}
    password: ${REDIS_PASSWORD:password}
  rabbitmq:
    host: ${TRAINEE_DETAILS_RABBITMQ_HOST:host.docker.internal}
    port: ${TRAINEE_DETAILS_RABBITMQ_PORT:5672}
    username: ${TRAINEE_DETAILS_RABBITMQ_USERNAME}
    password: ${TRAINEE_DETAILS_RABBITMQ_PASSWORD}
    ssl.enabled: ${TRAINEE_DETAILS_RABBITMQ_USE_SSL:false}

logging:
  level:
    root: INFO

sentry:
  dsn: ${SENTRY_DSN:}
  environment: ${application.environment}

application:
  aws:
    sqs:
      event: ${EVENT_QUEUE_URL:}
  environment: ${ENVIRONMENT:local}
  rabbit:
    coj-signed:
      exchange: ${COJ_SIGNED_RABBIT_EXCHANGE:}
      routing-key: ${COJ_SIGNED_RABBIT_ROUTING_KEY:}
  signature:
    secret-key: ${SIGNATURE_SECRET_KEY}
    expire-after:  # Minutes
      default: 1440
      uk.nhs.hee.trainee.details.dto.PlacementDto: ${ SIGNATURE_PLACEMENT_EXPIRY:1440 }
      uk.nhs.hee.trainee.details.dto.ProgrammeMembershipDto: ${ SIGNATURE_PROGRAMME_MEMBERSHIP_EXPIRY:1440 }

com:
  amazonaws:
    xray:
      emitters:
        daemon-address: ${AWS_XRAY_DAEMON_ADDRESS:}

mongock:
  migration-scan-package: uk.nhs.hee.trainee.details.migration
