server:
  port: 8203
  servlet:
    context-path: /trainee

spring:
  cloud:
    aws:
      endpoint: ${AWS_ENDPOINT:}
  data:
    mongodb:
      uri: mongodb://${DB_USER:admin}:${DB_PASSWORD:pwd}@${DB_HOST:localhost}:${DB_PORT:27017}/${DB_NAME:trainee}?authSource=admin
      auto-index-creation: true
      uuid-representation: standard
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      ssl:
        enabled: ${REDIS_SSL:false}
      user: ${REDIS_USER:default}
      password: ${REDIS_PASSWORD:password}

logging:
  level:
    root: INFO

sentry:
  dsn: ${SENTRY_DSN:}
  environment: ${application.environment}

application:
  aws:
    sns:
      coj-signed: ${TOPIC_ARN_COJ_SIGNED}
      gmc-details-provided: ${TOPIC_ARN_GMC_DETAILS_PROVIDED}
    sqs:
      event: ${EVENT_QUEUE_URL:}
      basic-details-update: ${BASIC_DETAILS_UPDATE_QUEUE_URL:}
      contact-details-update: ${CONTACT_DETAILS_UPDATE_QUEUE_URL:}
      gdc-details-update: ${GDC_DETAILS_UPDATE_QUEUE_URL:}
      gmc-details-update: ${GMC_DETAILS_UPDATE_QUEUE_URL:}
      personal-info-update: ${PERSONAL_INFO_UPDATE_QUEUE_URL:}
      person-owner-update: ${PERSON_OWNER_UPDATE_QUEUE_URL:}
  environment: ${ENVIRONMENT:local}
  features:
    ltft:
      pilot:
        start-date: 2025-04-28
        deaneries:
          - North West London
          - North Central and East London
          - South London
          - South West
  signature:
    secret-key: ${SIGNATURE_SECRET_KEY}
    expire-after:  # Minutes
      default: 1440
      uk.nhs.hee.trainee.details.dto.PlacementDto: ${ SIGNATURE_PLACEMENT_EXPIRY:1440 }
      uk.nhs.hee.trainee.details.dto.ProgrammeMembershipDto: ${ SIGNATURE_PROGRAMME_MEMBERSHIP_EXPIRY:1440 }
  template-versions:
    programme-confirmation: v1.0.0
  timezone: Europe/London

com:
  amazonaws:
    xray:
      emitters:
        daemon-address: ${AWS_XRAY_DAEMON_ADDRESS:}

mongock:
  migration-scan-package: uk.nhs.hee.trainee.details.migration

service:
  actions:
    host: ${TRAINEE_ACTIONS_HOST:localhost}
    port: ${TRAINEE_ACTIONS_PORT:8212}
    url: http://${service.actions.host}:${service.actions.port}/actions
  forms:
    host: ${TRAINEE_FORMS_HOST:localhost}
    port: ${TRAINEE_FORMS_PORT:8207}
    url: http://${service.forms.host}:${service.forms.port}/forms
  notifications:
    host: ${TRAINEE_NOTIFICATIONS_HOST:localhost}
    port: ${TRAINEE_NOTIFICATIONS_PORT:8211}
    url: http://${service.notifications.host}:${service.notifications.port}/notifications
  reference:
    host: ${TRAINEE_REFERENCE_HOST:localhost}
    port: ${TRAINEE_REFERENCE_PORT:8205}
    url: http://${service.reference.host}:${service.reference.port}/reference
