server:
  port: 8203
  servlet:
    context-path: /trainee

spring:
  data:
    mongodb:
      uri: mongodb://${DB_USER:admin}:${DB_PASSWORD:pwd}@${DB_HOST:localhost}:${DB_PORT:27017}/${DB_NAME:trainee}?authSource=admin

logging:
  level:
    root: INFO

sentry:
  dsn: ${SENTRY_DSN:}
  environment: ${SENTRY_ENVIRONMENT:local}

application:
  aws:
    sqs:
      event: ${EVENT_QUEUE_URL:}
  signature:
    secret-key: ${SIGNATURE_SECRET_KEY}
    expire-after:  # Minutes
      default: 1440
      uk.nhs.hee.trainee.details.dto.PlacementDto: ${ SIGNATURE_PLACEMENT_EXPIRY:1440 }
      uk.nhs.hee.trainee.details.dto.ProgrammeMembershipDto: ${ SIGNATURE_PROGRAMME_MEMBERSHIP_EXPIRY:1440 }

mongock:
  migration-scan-package: uk.nhs.hee.trainee.details.migration

dsp:
  client-id: ${DSP_CLIENT_ID:}
  client-secret: ${DSP_CLIENT_SECRET:}
  redirect-uri: ${DSP_REDIRECT_URI:}
  par-endpoint: ${DSP_PAR_ENDPOINT:}
  authorize-endpoint: ${DSP_AUTHORIZE_ENDPOINT:}
  token-issuer: ${DSP_TOKEN_ISSUER:}
  token-audience: ${DSP_TOKEN_AUDIENCE:}
  token-signing-key: ${DSP_TOKEN_SIGNING_KEY:}
  token-issue-endpoint: ${DSP_TOKEN_ISSUE_ENDPOINT:}
