name: CI/CD

on:
  push:
    branches:
      - TIS21-8924-integrate-ecr-scan

jobs:
  get-context:
    name: Check if debug enabled
    runs-on: ubuntu-latest
    outputs:
      runner-debug: ${{ runner.debug }}
    steps:
      - run: echo "Loading context variables"
  ci-cd:
    name: Build
    needs: get-context
    uses: health-education-england/.github/.github/workflows/build-gradle.yml@TIS21-8924-integrate-ecr-scan
    with:
      cluster-prefix: trainee
      publish-build-scan: ${{ needs.get-context.outputs.runner-debug == '1' }}
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}

  ecr-image-scan:
    needs: ci-cd
    uses: health-education-england/.github/.github/workflows/ecr-image-scan.yml@TIS21-8924-integrate-ecr-scan
    with:
      ecr-repository: ${{ github.event.repository.name }}
      image-tag: ${{ github.sha }}
