name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  ci-cd:
    name: Build and deploy
    uses: health-education-england/.github/.github/workflows/ci-cd-gradle.yml@main
    with:
      cluster-prefix: trainee
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
